language: rust

cache: cargo

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode9.4
    - os: windows
      before_script:
        - choco install googlechrome 

script:
  - cargo test --doc

addons:
  chrome: stable