language: rust

cache: cargo

matrix:
  include:
    - os: linux
    - os: osx
    - os: windows
      before_script:
        - choco install googlechrome 

script:
  - cargo test --doc

addons:
  chrome: stable