[package]
name = "alcro"
version = "0.2.3"
authors = ["Srinivasa <m.srinivasa1234@gmail.com>"]
edition = "2018"
description = "A library to create desktop apps using rust and modern web technologies"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/Srinivasa314/alcro"

[dependencies]
tempdir = "0.3.7"
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.58"
crossbeam-channel = "0.4.4"
tinyfiledialogs = "3.3.10"
libc = "0.2.79"
serde_derive = "1.0.116"
dashmap = "3.11.10"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["namedpipeapi" , "synchapi" , "handleapi" ] }
os_str_bytes = "2.3.2"

[dev-dependencies]
actix-web = "3.1.0"
actix-rt = "1.1.1"
rust-embed = "5.6.0"
mime_guess = "2.0.3"
futures = "0.3.6"
